### ISSUE TITLE
Question: Why can 'Timer.start' fail?

### ISSUE THREAD

**Issue by hbr** [aantron/luv#103]
Both `nodejs` and `luv` are base on `libuv`. In `luv` the function `Timer.start` can fail, in `nodejs` the function `setTimeout` cannot fail. Both functions are based on the same `libuv` function.

Can the corresponding `libuv` function fail? From its interface it is clear that in returns an `int` which theoretically can be negative and therefore signal an error. However, is this really possible since memory for the timer must be given as an argument?

**Comment by aantron** [comment]
It looks like `uv_timer_start` can fail due to invalid state of the libuv handle itself, if `Luv.Handle.is_closing timer`. From https://github.com/libuv/libuv/blob/285a5ea819035ff777b8b7c6a367f3f5b55d8809/src/timer.c#L67-L95:

```c
int uv_timer_start(uv_timer_t* handle,
                   uv_timer_cb cb,
                   uint64_t timeout,
                   uint64_t repeat) {
  uint64_t clamped_timeout;

  if (uv__is_closing(handle) || cb == NULL)
    return UV_EINVAL;

  if (uv__is_active(handle))
    uv_timer_stop(handle);

  clamped_timeout = handle->loop->time + timeout;
  if (clamped_timeout < timeout)
    clamped_timeout = (uint64_t) -1;

  handle->timer_cb = cb;
  handle->timeout = clamped_timeout;
  handle->repeat = repeat;
  /* start_id is the second index to be compared in timer_less_than() */
  handle->start_id = handle->loop->timer_counter++;

  heap_insert(timer_heap(handle->loop),
              (struct heap_node*) &handle->heap_node,
              timer_less_than);
  uv__handle_start(handle);

  return 0;
}
```

The `cb == NULL` condition will never be triggered by usage through Luv:

https://github.com/aantron/luv/blob/d1c1a4e732cee9731e890b9972701fc11ceba03f/src/timer.ml#L13-L28

So, in practice, it can only fail due to a bug in usage by the user, rather than any genuine runtime error. Luv faithfully exposes the libuv API and is meant for integration into other libraries. If you are using Luv directly and are confident that your program won't misuse the handle, or if your larger library is written in such a way as to make that impossible (e.g. it's always a fresh handle, or from a managed pool, like probably in Node), I think you can assume that `uv_timer_start` does not fail. This is, however, not future proof, but I think it's unlikely to change for the same reasons you think it shouldn't fail :)

By the way, I inherently answer all questions such as this one, including when I (very often) have them myself, by glancing in the libuv source code, and I encourage you to do that yourself, as well, as it saves a roundtrip. In this case, just cloning the libuv repo and doing `git grep -n uv_timer_start` revealed only one hit outside of test cases, docs, comments etc.:

```
src/timer.c:67:int uv_timer_start(uv_timer_t* handle,
```

which immediately gave me this answer.

**Comment by aantron** [comment]
The linked commit adds an answer to this particular question to the docs:

https://aantron.github.io/luv/luv/Luv/Timer/index.html#val-start

> As of Luv 0.5.7 and libuv 1.41.0 (March 2021), this function can fail only if the timer handle is currently closing, i.e.
>
> ```ocaml
>  Luv.Handle.is_closing timer = true
> ```

**Comment by aantron** [comment]
(Even if you do end up looking in libuv source for other questions, but find something that should be in the Luv docs, please do post an issue/make a PR, and we will add it).

**Comment by hbr** [comment]
Thanks for the excellent clarification.

Regards
Helmut
