### ISSUE TITLE
Build error: luv_unix cannot find `uv.h`

### ISSUE THREAD

**Issue by zbaylin** [aantron/luv#108]
**OS:** macOS 11

**Problem:** I try building `luv_unix` with `dune build -p luv,luv_unix` and I get the following error:
```
luv_unix.c:9:10: fatal error: 'uv.h' file not found
#include <uv.h>
         ^~~~~~
```

I assume this is because the `INCLUDE_PATH` is not setup properly for `luv_unix`, unlike `luv.c`.

**Comment by aantron** [comment]
It is most likely an instance of https://github.com/ocaml/dune/issues/4121, an upstream bug I reported to Dune, and is the reason I was delaying merging `luv_unix`.

Try working around it by installing a system-wide libuv (from Homebrew?), then removing it when done developing.

The CI is probably going to be pretty broken because of this. I'll look into seeing how far it can be fixed today. If you get the build working locally (it works for me), don't worry about fixing the CI &mdash; I'll take care of it asychronously.

**Comment by aantron** [comment]
(You can fully verify that it's due to https://github.com/ocaml/dune/issues/4121 by following the repro instructions in the issue; all the `opam` commands before `git clone` are about showing that the setup works outside of a monorepo, and Dune only starts doing the wrong thing with include paths for sibling local packages.)

**Comment by zbaylin** [comment]
@aantron Ah that makes sense. Installing the system header works for now -- I'll let you decide if this should remain open or if it should be closed since the issue is with `dune` rather than `luv`. 

Thanks!

**Comment by aantron** [comment]
Great :) I'll leave it open as a reminder in this repo, that there is still an issue to address.

**Comment by aantron** [comment]
I worked around this in 150c30545c9f0e35ac787a0610016a133511f599.
