### ISSUE TITLE
What about lwt?

### ISSUE THREAD

**Issue by benkb** [aantron/luv#41]
There are few mentions of lwt. But it would nice to have a few more words about the relationship of luv to lwt. Is luv thought to be a replacement? 

from lwt: Asynchronous programming with promises.
from libuv: offers an asynchronous, event-driven style of programming

**Comment by aantron** [comment]
Luv corresponds to `lwt.unix`, so modules `Lwt_unix`, `Lwt_main`, etc. There is otherwise no relationship. In the future, there might be an implementation of `lwt.unix` over Luv.

There are examples of a simpler way of using the Lwt core over Luv, a way that is incompatible with current `lwt.unix` usage. Such an example is here: https://github.com/aantron/luv/blob/0eae7f30ef99157bda77c62e0cb82169410de583/example/http_get_lwt/http_get_lwt.ml.

You can check out that commit 0eae7f30ef99157bda77c62e0cb82169410de583 to play around with that Lwt/Luv integration.

**Comment by aantron** [comment]
And replying to an earlier edit, yes, Lwt APIs consistently use promises, while Luv exposes only callbacks, but those are both event-driven style, and one is easily convertible into another. In fact, the commit I linked above has a functor in Luv for doing that.

**Comment by benkb** [comment]
great thanks, this should go into a wiki :-)

**Comment by aantron** [comment]
Yes, probably, but I haven't written yet, mainly in expectation of doing some integration work soon-ish :) So it might be a little early to write that wiki, because the information would become out of date very soon. On the other hand, if no proper integration becomes available after some time, it's probably best to just describe the current state in the docs. Let's leave this open, as a reminder to decide either way at some point.

**Comment by aantron** [comment]
(In fact, the issue for the coding work of it is #1, as you may have seen)

**Comment by benkb** [comment]
> (In fact, the issue for the coding work of it is #1, as you may have seen)

A thought while reading this. Lwt, a great piece of software probably one of the most used Ocaml libraries overall, forces me into a style of programming I don't like. I have the impression that luv makes things a lot easier for me (a simple user). 
So while I have great respect of your experiment in #1, I simply hope, that the rather unwieldy syntax of lwt doesn't leak into luv.

**Comment by aantron** [comment]
It wouldn't break into Luv. #1 is about working entirely in the Lwt repo. It would be a change to Lwt only, that would have no effect on Luv (except patches for any bugs found in the process), and should also be mostly transparent to Lwt users as well.

**Comment by aantron** [comment]
In other words, #1 isn't about modifying Luv to turn it into Lwt. It's about using Luv as is as the lowest layer of `lwt.unix`.

**Comment by aantron** [comment]
I'm closing this in favor of issue https://github.com/ocsigen/lwt/issues/813 "A Roadmap for Porting lwt.unix to libuv" in Lwt. As we work on that, the relationship between Luv and Lwt will become more clear, and we will adjust the docs along the way.
