### ISSUE TITLE
Question about `Luv.File.stat` and `st_mode`

### ISSUE THREAD

**Issue by bryphe** [aantron/luv#68]
I was looking at using the `Luv.File.stat` method defined here: https://github.com/aantron/luv/blob/12298819f5109aedf8b22669c2f8794379c6348c/src/file.mli#L511 

which gives a `Stat.t` record like:
```
type t = {
    ...
    mode : Mode.numeric;
   ...
  }
```

I'd like to use the `mode` property to figure out if the requested path corresponds to a directory, file, or symlink.

We should be able to use the `mode` against some platform-defined constants, like `S_IFDIR` to represent this, ie:
https://github.com/nodejs/node/blob/d3a8a23089af06bb047bf9bad7531fbfc70f6314/src/node_file.cc#L954

I was wondering if you had any thoughts on exposing some equivalent API in `luv`?

We have the `Mode` type, but that looks geared mainly towards permission modes (the `st_mode` actually represents both permissions and file types).

One option would be to do like `node` does, and expose methods in that stat module, like:
- `isDirectory: Stat.t -> bool`
- `isFile: Stat.t -> bool`
- `isBlockDevice: Stat.t -> bool`
- `isCharacterDevice: Stat.t -> bool`
- `isSymbolicLink: Stat.t -> bool`
- `isFIFO: Stat.t -> bool`
- `isSocket: Stat.t -> bool`

(under the hood, these would check the `st_mode` bitmask against the constants like `S_IFDIR`).

https://github.com/nodejs/node/blob/a4e273baf43910ba9e5c66949e56b919f8614fb9/lib/internal/fs/utils.js#L328

There might be other, better ways to model this though - you might have ideas already @aantron (or I could be missing something obvious, too!)

**Comment by aantron** [comment]
> We have the `Mode` type, but that looks geared mainly towards permission modes (the `st_mode` actually represents both permissions and file types).

It's not intended to be geared only towards permissions. That's just an initial set of constants I picked that I figured would be present on all systems. In fact, even my original guess was an overestimate: https://github.com/aantron/luv/commit/226446ea8bb21e3a4feebb0ad596dc6536367796#diff-2fd0af3dbba1d96e776e4224fd49dcd9R20.

I propose to simply add the constants to `Mode.t`. If any turn out in CI or for future users to be undefined, we can do the same for them as the above commit did for `S_ISUID` and `S_ISGID`, which is to define them as zero on those systems, so that they don't affect tests and are not ORed into any flag sets.

I should probably start documenting this behavior in `file.mli`.

I'm also tempted to case `` `NUMERIC`` as `` `Numeric``, to more greatly distinguish it from the constants.

**Comment by aantron** [comment]
Given this statement in the Linux man page:

> POSIX.1-1990 did not describe the S_IFMT, S_IFSOCK, S_IFLNK, S_IFREG, S_IFBLK, S_IFDIR, S_IFCHR, S_IFIFO, S_ISVTX constants, but instead demanded the use of the macros S_ISDIR(), etc. The S_IF* constants are present in POSIX.1-2001 and later.

perhaps testing functions are indeed better. However, I also see an `_S_IFDIR` [here](https://docs.microsoft.com/en-us/cpp/c-runtime-library/stat-structure-st-mode-field-constants?view=vs-2019). Probably some testing should be done to figure out what will work best for most systems. I'd prefer to add just flags, but it's better to add a method if the flags will end up working in fewer cases, because then the option of using the flags will be misleading.

**Comment by aantron** [comment]
(Although, technically, we can still do a macro test internally even if we expose a flag-like constructor, because the entire interface in `Mode` is abstract.)

**Comment by aantron** [comment]
The constants are present, without leading underscores, on recent MinGW and (naturally) on Linux. I didn't check macOS, but I expect it has them, too.

I think we can just add the constants and give them the same simple implementation as e.g. `S_IRUSR` has.
