### ISSUE TITLE
dependency error while installing luv

### ISSUE THREAD

**Issue by lubegasimon** [aantron/luv#88]
When installing `luv` using `opam install luv`, it is required that the following operation need to be performed
```
The following actions will be performed:
  - install conf-pkg-config 1.3    [required by ctypes]
  - install ctypes          0.17.1 [required by luv]
  - install luv             0.5.6
  ```
However, `conf-pkg-config` required `pkg-config` to be installed on the system first
```
<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build conf-pkg-config 1.3
+- 
- No changes have been performed

The packages you requested declare the following system dependencies. Please make sure
they are installed before retrying:
    pkg-config
```
But it's not clear how to install `pkg-config`.

I confess that I should've reported this to https://github.com/freedesktop/pkg-config, but the project seems to not have been maintained for long, thus unable to file a ticket there. Any hints will be appreciated  🙂!

**Comment by aantron** [comment]
This is actually an issue in `ctypes` rather than in `pkg-config` &mdash; `ctypes` has a spurious dependency on `pkg-config`. I patched this upstream in `ctypes` in https://github.com/ocamllabs/ocaml-ctypes/pull/631, and it was released in [`ctypes` 0.18.0](https://github.com/ocamllabs/ocaml-ctypes/blob/0.18.0/CHANGES.md#ctypes-0180), but it the release hasn't yet been merged into opam-repository. The opam-repository PR for that is here: https://github.com/ocaml/opam-repository/pull/17614.

You should be able to work around this by either pinning `ctypes` to the git commit that was release 0.18.0, or installing `pkg-config`, a system package, using either your system package manager, or with `opam depext conf-pkg-config`.

**Comment by lubegasimon** [comment]
That’s helpful, thank you!

**Comment by aantron** [comment]
Ctypes 0.18.0 is now in opam, hopefully fully resolving this issue.

**Comment by lubegasimon** [comment]
Cool, I’ll give it another try. Thanks
